# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'DropdownDemo.xcworkspace'

target 'DropdownDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
#   Pods for DropdownDemo

pod 'Masonry', '~> 0.6.3'
pod 'SDWebImage/Core', '~> 3.7.3'
pod 'YYModel'

target 'DropdownDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DropdownDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
